app = "lbc-worker-production"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  [services.concurrency]
    hard_limit = 2
    soft_limit = 1

[experimental]
cmd = ["poetry", "run", "python", "manage.py", "start_worker"]
