# fly.toml file generated for lbc-staging on 2022-04-21T15:15:10+01:00

app = "lbc-production"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "make release"
  strategy = "rolling"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
    
  [[services.http_checks]]
    grace_period = "30s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 3000
    restart_limit = 6
    tls_skip_verify = true
    [services.http_checks.headers]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
