app = "leftbookclub-prod"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = 8080
STRIPE_LIVE_MODE = "True"

[deploy]
release_command = "make release"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
