app = "lbc-worker-production"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "make release"
  strategy = "rolling"

[[services]]
  [services.concurrency]
    hard_limit = 1
    soft_limit = 1
    
  [[services.http_checks]]
    grace_period = "30s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 3000
    restart_limit = 6
    tls_skip_verify = true
    [services.http_checks.headers]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"

[experimental]
cmd = ["poetry", "run", "python", "manage.py", "run_cron_tasks"]
