# Generated by Django 4.0.3 on 2022-03-31 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("djstripe", "0011_alter_invoice_charge_alter_invoice_customer_and_more"),
        ("app", "0002_homepage"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='LBCProduct',
        #     fields=[
        #     ],
        #     options={
        #         'proxy': True,
        #         'indexes': [],
        #         'constraints': [],
        #     },
        #     bases=('djstripe.product',),
        # ),
        migrations.CreateModel(
            name="FeaturedContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="djstripe.product",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Content",
            },
        ),
    ]
