# Generated by Django 4.0.3 on 2022-03-31 10:54

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("app", "0004_shippingzone"),
        ("app", "0005_remove_shippingzone_countries_mode"),
        ("app", "0006_alter_shippingzone_code"),
    ]

    dependencies = [
        ("app", "0003_lbcproduct_featuredcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="Nickname for admin use", max_length=300
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The code is used to identify the right price in Stripe. Stripe product prices with metadata UK: 4.00 will be selected, for example.",
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                    ),
                ),
                (
                    "countries",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
            ],
        ),
    ]
