# Generated by Django 4.0.3 on 2022-04-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_shippingzone_squashed_0006_alter_shippingzone_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredcontent",
            name="current_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.lbcproduct",
            ),
        ),
    ]
