# Generated by Django 4.0.4 on 2022-04-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_blogpage_feed_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="date",
        ),
    ]
