# Generated by Django 4.0.4 on 2022-04-14 13:04

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_bookpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.RichTextBlock(
                            features=["h3", "h4", "bold", "italic", "link", "ol", "ul"],
                            template="app/content/text.html",
                        ),
                    ),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(
                            template="app/content/embed.html"
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
