# Generated by Django 4.0.3 on 2022-04-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_customimage_informationpage_imagerendition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="feed_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.customimage",
            ),
        ),
    ]
