# Generated by Django 4.0.3 on 2022-04-12 15:59

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_blogpage_body_alter_blogpage_feed_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.RichTextBlock(
                            features=["h3", "h4", "bold", "italic", "link", "ol", "ul"],
                            template="app/content/text.html",
                        ),
                    ),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(
                            template="app/content/embed.html"
                        ),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.RichTextBlock(
                            features=["h3", "h4", "bold", "italic", "link", "ol", "ul"],
                            template="app/content/text.html",
                        ),
                    ),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(
                            template="app/content/embed.html"
                        ),
                    ),
                ]
            ),
        ),
    ]
