# Generated by Django 4.0.4 on 2022-04-21 09:35

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_blogindexpage_canonical_url_blogindexpage_og_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=wagtail.core.fields.RichTextField(max_length=250),
        ),
    ]
