# Generated by Django 4.0.4 on 2022-04-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_merchandisepage_remove_bookpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredcontent",
            name="current_book",
        ),
    ]
