# Generated by Django 4.0.4 on 2022-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_user_address1_user_address2_user_birthday_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="old_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address1",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address2",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="occupation",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="tel",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
