# Generated by Django 4.0.4 on 2022-04-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_featuredcontent_current_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredcontent",
            name="current_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.bookpage",
            ),
        ),
    ]
