# Generated by Django 4.0.4 on 2022-04-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010_alter_customer_balance"),
        ("app", "0012_lbccustomer"),
    ]

    operations = [
        migrations.CreateModel(
            name="LBCSubscription",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("djstripe.subscription",),
        ),
    ]
