# Generated by Django 4.0.4 on 2022-04-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_featuredcontent_current_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookpage",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AddField(
            model_name="bookpage",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
