# Generated by Django 4.0.4 on 2022-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_shippingzone_rate_shippingzone_rate_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="rest_of_world",
            field=models.BooleanField(
                blank=True,
                help_text="If selected, this zone's shipping rate will be used as the default shipping rate.",
                null=True,
            ),
        ),
    ]
