# Generated by Django 4.0.4 on 2022-04-26 17:51

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_shippingzone_rest_of_world"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingzone",
            name="countries",
            field=django_countries.fields.CountryField(
                blank=True, max_length=1000, multiple=True
            ),
        ),
    ]
