# Generated by Django 4.0.4 on 2022-04-27 13:07

from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations, models

import app.models.wagtail


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("app", "0016_alter_shippingzone_countries"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlanPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "struct_org_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Organization", "Organization"),
                            ("Airline", "Organization > Airline"),
                            ("Corporation", "Organization > Corporation"),
                            (
                                "EducationalOrganization",
                                "Organization > EducationalOrganization",
                            ),
                            (
                                "CollegeOrUniversity",
                                "Organization > EducationalOrganization > CollegeOrUniversity",
                            ),
                            (
                                "ElementarySchool",
                                "Organization > EducationalOrganization > ElementarySchool",
                            ),
                            (
                                "HighSchool",
                                "Organization > EducationalOrganization > HighSchool",
                            ),
                            (
                                "MiddleSchool",
                                "Organization > EducationalOrganization > MiddleSchool",
                            ),
                            (
                                "Preschool",
                                "Organization > EducationalOrganization > Preschool",
                            ),
                            (
                                "School",
                                "Organization > EducationalOrganization > School",
                            ),
                            (
                                "GovernmentOrganization",
                                "Organization > GovernmentOrganization",
                            ),
                            ("LocalBusiness", "Organization > LocalBusiness"),
                            (
                                "AnimalShelter",
                                "Organization > LocalBusiness > AnimalShelter",
                            ),
                            (
                                "AutomotiveBusiness",
                                "Organization > LocalBusiness > AutomotiveBusiness",
                            ),
                            (
                                "AutoBodyShop",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoBodyShop",
                            ),
                            (
                                "AutoDealer",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoDealer",
                            ),
                            (
                                "AutoPartsStore",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoPartsStore",
                            ),
                            (
                                "AutoRental",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoRental",
                            ),
                            (
                                "AutoRepair",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoRepair",
                            ),
                            (
                                "AutoWash",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoWash",
                            ),
                            (
                                "GasStation",
                                "Organization > LocalBusiness > AutomotiveBusiness > GasStation",
                            ),
                            (
                                "MotorcycleDealer",
                                "Organization > LocalBusiness > AutomotiveBusiness > MotorcycleDealer",
                            ),
                            (
                                "MotorcycleRepair",
                                "Organization > LocalBusiness > AutomotiveBusiness > MotorcycleRepair",
                            ),
                            ("ChildCare", "Organization > LocalBusiness > ChildCare"),
                            ("Dentist", "Organization > LocalBusiness > Dentist"),
                            (
                                "DryCleaningOrLaundry",
                                "Organization > LocalBusiness > DryCleaningOrLaundry",
                            ),
                            (
                                "EmergencyService",
                                "Organization > LocalBusiness > EmergencyService",
                            ),
                            (
                                "FireStation",
                                "Organization > LocalBusiness > EmergencyService > FireStation",
                            ),
                            (
                                "Hospital",
                                "Organization > LocalBusiness > EmergencyService > Hospital",
                            ),
                            (
                                "PoliceStation",
                                "Organization > LocalBusiness > EmergencyService > PoliceStation",
                            ),
                            (
                                "EmploymentAgency",
                                "Organization > LocalBusiness > EmploymentAgency",
                            ),
                            (
                                "EntertainmentBusiness",
                                "Organization > LocalBusiness > EntertainmentBusiness",
                            ),
                            (
                                "AdultEntertainment",
                                "Organization > LocalBusiness > EntertainmentBusiness > AdultEntertainment",
                            ),
                            (
                                "AmusementPark",
                                "Organization > LocalBusiness > EntertainmentBusiness > AmusementPark",
                            ),
                            (
                                "ArtGallery",
                                "Organization > LocalBusiness > EntertainmentBusiness > ArtGallery",
                            ),
                            (
                                "Casino",
                                "Organization > LocalBusiness > EntertainmentBusiness > Casino",
                            ),
                            (
                                "ComedyClub",
                                "Organization > LocalBusiness > EntertainmentBusiness > ComedyClub",
                            ),
                            (
                                "MovieTheater",
                                "Organization > LocalBusiness > EntertainmentBusiness > MovieTheater",
                            ),
                            (
                                "NightClub",
                                "Organization > LocalBusiness > EntertainmentBusiness > NightClub",
                            ),
                            (
                                "FinancialService",
                                "Organization > LocalBusiness > FinancialService",
                            ),
                            (
                                "AccountingService",
                                "Organization > LocalBusiness > FinancialService > AccountingService",
                            ),
                            (
                                "AutomatedTeller",
                                "Organization > LocalBusiness > FinancialService > AutomatedTeller",
                            ),
                            (
                                "BankOrCreditUnion",
                                "Organization > LocalBusiness > FinancialService > BankOrCreditUnion",
                            ),
                            (
                                "InsuranceAgency",
                                "Organization > LocalBusiness > FinancialService > InsuranceAgency",
                            ),
                            (
                                "FoodEstablishment",
                                "Organization > LocalBusiness > FoodEstablishment",
                            ),
                            (
                                "Bakery",
                                "Organization > LocalBusiness > FoodEstablishment > Bakery",
                            ),
                            (
                                "BarOrPub",
                                "Organization > LocalBusiness > FoodEstablishment > BarOrPub",
                            ),
                            (
                                "Brewery",
                                "Organization > LocalBusiness > FoodEstablishment > Brewery",
                            ),
                            (
                                "CafeOrCoffeeShop",
                                "Organization > LocalBusiness > FoodEstablishment > CafeOrCoffeeShop",
                            ),
                            (
                                "FastFoodRestaurant",
                                "Organization > LocalBusiness > FoodEstablishment > FastFoodRestaurant",
                            ),
                            (
                                "IceCreamShop",
                                "Organization > LocalBusiness > FoodEstablishment > IceCreamShop",
                            ),
                            (
                                "Restaurant",
                                "Organization > LocalBusiness > FoodEstablishment > Restaurant",
                            ),
                            (
                                "Winery",
                                "Organization > LocalBusiness > FoodEstablishment > Winery",
                            ),
                            (
                                "GovernmentOffice",
                                "Organization > LocalBusiness > GovernmentOffice",
                            ),
                            (
                                "PostOffice",
                                "Organization > LocalBusiness > GovernmentOffice > PostOffice",
                            ),
                            (
                                "HealthAndBeautyBusiness",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness",
                            ),
                            (
                                "BeautySalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > BeautySalon",
                            ),
                            (
                                "DaySpa",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > DaySpa",
                            ),
                            (
                                "HairSalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > HairSalon",
                            ),
                            (
                                "HealthClub",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > HealthClub",
                            ),
                            (
                                "NailSalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > NailSalon",
                            ),
                            (
                                "TattooParlor",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > TattooParlor",
                            ),
                            (
                                "HomeAndConstructionBusiness",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness",
                            ),
                            (
                                "Electrician",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Electrician",
                            ),
                            (
                                "GeneralContractor",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > GeneralContractor",
                            ),
                            (
                                "HVACBusiness",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > HVACBusiness",
                            ),
                            (
                                "HousePainter",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > HousePainter",
                            ),
                            (
                                "Locksmith",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Locksmith",
                            ),
                            (
                                "MovingCompany",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > MovingCompany",
                            ),
                            (
                                "Plumber",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Plumber",
                            ),
                            (
                                "RoofingContractor",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > RoofingContractor",
                            ),
                            (
                                "InternetCafe",
                                "Organization > LocalBusiness > InternetCafe",
                            ),
                            (
                                "LegalService",
                                "Organization > LocalBusiness > LegalService",
                            ),
                            (
                                "Attorney",
                                "Organization > LocalBusiness > LegalService > Attorney",
                            ),
                            (
                                "Notary",
                                "Organization > LocalBusiness > LegalService > Notary",
                            ),
                            ("Library", "Organization > LocalBusiness > Library"),
                            (
                                "LodgingBusiness",
                                "Organization > LocalBusiness > LodgingBusiness",
                            ),
                            (
                                "BedAndBreakfast",
                                "Organization > LocalBusiness > LodgingBusiness > BedAndBreakfast",
                            ),
                            (
                                "Campground",
                                "Organization > LocalBusiness > LodgingBusiness > Campground",
                            ),
                            (
                                "Hostel",
                                "Organization > LocalBusiness > LodgingBusiness > Hostel",
                            ),
                            (
                                "Hotel",
                                "Organization > LocalBusiness > LodgingBusiness > Hotel",
                            ),
                            (
                                "Motel",
                                "Organization > LocalBusiness > LodgingBusiness > Motel",
                            ),
                            (
                                "Resort",
                                "Organization > LocalBusiness > LodgingBusiness > Resort",
                            ),
                            (
                                "ProfessionalService",
                                "Organization > LocalBusiness > ProfessionalService",
                            ),
                            (
                                "RadioStation",
                                "Organization > LocalBusiness > RadioStation",
                            ),
                            (
                                "RealEstateAgent",
                                "Organization > LocalBusiness > RealEstateAgent",
                            ),
                            (
                                "RecyclingCenter",
                                "Organization > LocalBusiness > RecyclingCenter",
                            ),
                            (
                                "SelfStorage",
                                "Organization > LocalBusiness > SelfStorage",
                            ),
                            (
                                "ShoppingCenter",
                                "Organization > LocalBusiness > ShoppingCenter",
                            ),
                            (
                                "SportsActivityLocation",
                                "Organization > LocalBusiness > SportsActivityLocation",
                            ),
                            (
                                "BowlingAlley",
                                "Organization > LocalBusiness > SportsActivityLocation > BowlingAlley",
                            ),
                            (
                                "ExerciseGym",
                                "Organization > LocalBusiness > SportsActivityLocation > ExerciseGym",
                            ),
                            (
                                "GolfCourse",
                                "Organization > LocalBusiness > SportsActivityLocation > GolfCourse",
                            ),
                            (
                                "HealthClub",
                                "Organization > LocalBusiness > SportsActivityLocation > HealthClub",
                            ),
                            (
                                "PublicSwimmingPool",
                                "Organization > LocalBusiness > SportsActivityLocation > PublicSwimmingPool",
                            ),
                            (
                                "SkiResort",
                                "Organization > LocalBusiness > SportsActivityLocation > SkiResort",
                            ),
                            (
                                "SportsClub",
                                "Organization > LocalBusiness > SportsActivityLocation > SportsClub",
                            ),
                            (
                                "StadiumOrArena",
                                "Organization > LocalBusiness > SportsActivityLocation > StadiumOrArena",
                            ),
                            (
                                "TennisComplex",
                                "Organization > LocalBusiness > SportsActivityLocation > TennisComplex",
                            ),
                            ("Store", "Organization > LocalBusiness > Store"),
                            (
                                "AutoPartsStore",
                                "Organization > LocalBusiness > Store > AutoPartsStore",
                            ),
                            (
                                "BikeStore",
                                "Organization > LocalBusiness > Store > BikeStore",
                            ),
                            (
                                "BookStore",
                                "Organization > LocalBusiness > Store > BookStore",
                            ),
                            (
                                "ClothingStore",
                                "Organization > LocalBusiness > Store > ClothingStore",
                            ),
                            (
                                "ComputerStore",
                                "Organization > LocalBusiness > Store > ComputerStore",
                            ),
                            (
                                "ConvenienceStore",
                                "Organization > LocalBusiness > Store > ConvenienceStore",
                            ),
                            (
                                "DepartmentStore",
                                "Organization > LocalBusiness > Store > DepartmentStore",
                            ),
                            (
                                "ElectronicsStore",
                                "Organization > LocalBusiness > Store > ElectronicsStore",
                            ),
                            (
                                "Florist",
                                "Organization > LocalBusiness > Store > Florist",
                            ),
                            (
                                "FurnitureStore",
                                "Organization > LocalBusiness > Store > FurnitureStore",
                            ),
                            (
                                "GardenStore",
                                "Organization > LocalBusiness > Store > GardenStore",
                            ),
                            (
                                "GroceryStore",
                                "Organization > LocalBusiness > Store > GroceryStore",
                            ),
                            (
                                "HardwareStore",
                                "Organization > LocalBusiness > Store > HardwareStore",
                            ),
                            (
                                "HobbyShop",
                                "Organization > LocalBusiness > Store > HobbyShop",
                            ),
                            (
                                "HomeGoodsStore",
                                "Organization > LocalBusiness > Store > HomeGoodsStore",
                            ),
                            (
                                "JewelryStore",
                                "Organization > LocalBusiness > Store > JewelryStore",
                            ),
                            (
                                "LiquorStore",
                                "Organization > LocalBusiness > Store > LiquorStore",
                            ),
                            (
                                "MensClothingStore",
                                "Organization > LocalBusiness > Store > MensClothingStore",
                            ),
                            (
                                "MobilePhoneStore",
                                "Organization > LocalBusiness > Store > MobilePhoneStore",
                            ),
                            (
                                "MovieRentalStore",
                                "Organization > LocalBusiness > Store > MovieRentalStore",
                            ),
                            (
                                "MusicStore",
                                "Organization > LocalBusiness > Store > MusicStore",
                            ),
                            (
                                "OfficeEquipmentStore",
                                "Organization > LocalBusiness > Store > OfficeEquipmentStore",
                            ),
                            (
                                "OutletStore",
                                "Organization > LocalBusiness > Store > OutletStore",
                            ),
                            (
                                "PawnShop",
                                "Organization > LocalBusiness > Store > PawnShop",
                            ),
                            (
                                "PetStore",
                                "Organization > LocalBusiness > Store > PetStore",
                            ),
                            (
                                "ShoeStore",
                                "Organization > LocalBusiness > Store > ShoeStore",
                            ),
                            (
                                "SportingGoodsStore",
                                "Organization > LocalBusiness > Store > SportingGoodsStore",
                            ),
                            (
                                "TireShop",
                                "Organization > LocalBusiness > Store > TireShop",
                            ),
                            (
                                "ToyStore",
                                "Organization > LocalBusiness > Store > ToyStore",
                            ),
                            (
                                "WholesaleStore",
                                "Organization > LocalBusiness > Store > WholesaleStore",
                            ),
                            (
                                "TelevisionStation",
                                "Organization > LocalBusiness > TelevisionStation",
                            ),
                            (
                                "TouristInformationCenter",
                                "Organization > LocalBusiness > TouristInformationCenter",
                            ),
                            (
                                "TravelAgency",
                                "Organization > LocalBusiness > TravelAgency",
                            ),
                            (
                                "MedicalOrganization",
                                "Organization > MedicalOrganization",
                            ),
                            ("Dentist", "Organization > MedicalOrganization > Dentist"),
                            (
                                "Hospital",
                                "Organization > MedicalOrganization > Hospital",
                            ),
                            (
                                "Pharmacy",
                                "Organization > MedicalOrganization > Pharmacy",
                            ),
                            (
                                "Physician",
                                "Organization > MedicalOrganization > Physician",
                            ),
                            ("NGO", "Organization > NGO"),
                            ("PerformingGroup", "Organization > PerformingGroup"),
                            (
                                "DanceGroup",
                                "Organization > PerformingGroup > DanceGroup",
                            ),
                            (
                                "MusicGroup",
                                "Organization > PerformingGroup > MusicGroup",
                            ),
                            (
                                "TheaterGroup",
                                "Organization > PerformingGroup > TheaterGroup",
                            ),
                            ("SportsOrganization", "Organization > SportsOrganization"),
                            (
                                "SportsTeam",
                                "Organization > SportsOrganization > SportsTeam",
                            ),
                        ],
                        default="",
                        help_text="If blank, no structured data will be used on this page.",
                        max_length=255,
                        verbose_name="Organization type",
                    ),
                ),
                (
                    "struct_org_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leave blank to use the site name in Settings > Sites",
                        max_length=255,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "struct_org_phone",
                    models.CharField(
                        blank=True,
                        help_text="Include country code for best results. For example: +1-216-555-8000",
                        max_length=255,
                        verbose_name="Telephone number",
                    ),
                ),
                (
                    "struct_org_address_street",
                    models.CharField(
                        blank=True,
                        help_text="House number and street. For example, 55 Public Square Suite 1710",
                        max_length=255,
                        verbose_name="Street address",
                    ),
                ),
                (
                    "struct_org_address_locality",
                    models.CharField(
                        blank=True,
                        help_text="City or locality. For example, Cleveland",
                        max_length=255,
                        verbose_name="City",
                    ),
                ),
                (
                    "struct_org_address_region",
                    models.CharField(
                        blank=True,
                        help_text="State, province, county, or region. For example, OH",
                        max_length=255,
                        verbose_name="State",
                    ),
                ),
                (
                    "struct_org_address_postal",
                    models.CharField(
                        blank=True,
                        help_text="Zip or postal code. For example, 44113",
                        max_length=255,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "struct_org_address_country",
                    models.CharField(
                        blank=True,
                        help_text="For example, USA. Two-letter ISO 3166-1 alpha-2 country code is also acceptable https://en.wikipedia.org/wiki/ISO_3166-1",
                        max_length=255,
                        verbose_name="Country",
                    ),
                ),
                (
                    "struct_org_geo_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Geographic latitude",
                    ),
                ),
                (
                    "struct_org_geo_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Geographic longitude",
                    ),
                ),
                (
                    "struct_org_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hours",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "days",
                                            wagtail.blocks.MultipleChoiceBlock(
                                                choices=[
                                                    ("Monday", "Monday"),
                                                    ("Tuesday", "Tuesday"),
                                                    ("Wednesday", "Wednesday"),
                                                    ("Thursday", "Thursday"),
                                                    ("Friday", "Friday"),
                                                    ("Saturday", "Saturday"),
                                                    ("Sunday", "Sunday"),
                                                ],
                                                help_text="For late night hours past 23:59, define each day in a separate block.",
                                                verbose_name="Days",
                                            ),
                                        ),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                verbose_name="Opening time"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                verbose_name="Closing time"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        verbose_name="Hours of operation",
                    ),
                ),
                (
                    "struct_org_actions",
                    wagtail.fields.StreamField(
                        [
                            (
                                "actions",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "action_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("OrderAction", "OrderAction"),
                                                    ("ReserveAction", "ReserveAction"),
                                                ],
                                                verbose_name="Action Type",
                                            ),
                                        ),
                                        (
                                            "target",
                                            wagtail.blocks.URLBlock(
                                                verbose_name="Target URL"
                                            ),
                                        ),
                                        (
                                            "language",
                                            wagtail.blocks.CharBlock(
                                                default="en-US",
                                                help_text="If the action is offered in multiple languages, create separate actions for each language.",
                                                verbose_name="Language",
                                            ),
                                        ),
                                        (
                                            "result_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("Reservation", "Reservation"),
                                                    (
                                                        "BusReservation",
                                                        "BusReservation",
                                                    ),
                                                    (
                                                        "EventReservation",
                                                        "EventReservation",
                                                    ),
                                                    (
                                                        "FlightReservation",
                                                        "FlightReservation",
                                                    ),
                                                    (
                                                        "FoodEstablishmentReservation",
                                                        "FoodEstablishmentReservation",
                                                    ),
                                                    (
                                                        "LodgingReservation",
                                                        "LodgingReservation",
                                                    ),
                                                    (
                                                        "RentalCarReservation",
                                                        "RentalCarReservation",
                                                    ),
                                                    (
                                                        "ReservationPackage",
                                                        "ReservationPackage",
                                                    ),
                                                    (
                                                        "TaxiReservation",
                                                        "TaxiReservation",
                                                    ),
                                                    (
                                                        "TrainReservation",
                                                        "TrainReservation",
                                                    ),
                                                ],
                                                help_text="Leave blank for OrderAction",
                                                required=False,
                                                verbose_name="Result Type",
                                            ),
                                        ),
                                        (
                                            "result_name",
                                            wagtail.blocks.CharBlock(
                                                help_text='Example: "Reserve a table", "Book an appointment", etc.',
                                                required=False,
                                                verbose_name="Result Name",
                                            ),
                                        ),
                                        (
                                            "extra_json",
                                            wagtail.blocks.RawHTMLBlock(
                                                form_classname="monospace",
                                                help_text="Additional JSON-LD inserted into the Action dictionary. Must be properties of https://schema.org/Action.",
                                                required=False,
                                                verbose_name="Additional action markup",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        verbose_name="Actions",
                    ),
                ),
                (
                    "struct_org_extra_json",
                    models.TextField(
                        blank=True,
                        help_text="Additional JSON-LD inserted into the Organization dictionary. Must be properties of https://schema.org/Organization or the selected organization type.",
                        verbose_name="Additional Organization markup",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("deliveries_per_year", models.IntegerField()),
                (
                    "description",
                    wagtail.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "pick_product_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<h3>Choose a book series</h3>",
                        help_text="Displayed if there are multiple products to pick from",
                        null=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.customimage",
                        verbose_name="Preview image",
                    ),
                ),
                ("products", models.ManyToManyField(blank=True, to="app.lbcproduct")),
                (
                    "struct_org_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="A photo of the facility. This photo will be cropped to 1:1, 4:3, and 16:9 aspect ratios automatically.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.customimage",
                        verbose_name="Photo of Organization",
                    ),
                ),
                (
                    "struct_org_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use the logo in Settings > Layout > Logo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.customimage",
                        verbose_name="Organization logo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="homepage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "membership_options",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        default="Choose your plan",
                                        form_classname="full title",
                                        null=True,
                                    ),
                                ),
                                (
                                    "plans",
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock(
                                            app.models.wagtail.MembershipPlanPage
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MembershipPlanPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("XUA", "ADB Unit of Account"),
                            ("AFN", "Afghan Afghani"),
                            ("AFA", "Afghan Afghani (1927–2002)"),
                            ("ALL", "Albanian Lek"),
                            ("ALK", "Albanian Lek (1946–1965)"),
                            ("DZD", "Algerian Dinar"),
                            ("ADP", "Andorran Peseta"),
                            ("AOA", "Angolan Kwanza"),
                            ("AOK", "Angolan Kwanza (1977–1991)"),
                            ("AON", "Angolan New Kwanza (1990–2000)"),
                            ("AOR", "Angolan Readjusted Kwanza (1995–1999)"),
                            ("ARA", "Argentine Austral"),
                            ("ARS", "Argentine Peso"),
                            ("ARM", "Argentine Peso (1881–1970)"),
                            ("ARP", "Argentine Peso (1983–1985)"),
                            ("ARL", "Argentine Peso Ley (1970–1983)"),
                            ("AMD", "Armenian Dram"),
                            ("AWG", "Aruban Florin"),
                            ("AUD", "Australian Dollar"),
                            ("ATS", "Austrian Schilling"),
                            ("AZN", "Azerbaijani Manat"),
                            ("AZM", "Azerbaijani Manat (1993–2006)"),
                            ("BSD", "Bahamian Dollar"),
                            ("BHD", "Bahraini Dinar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BBD", "Barbadian Dollar"),
                            ("BYN", "Belarusian Ruble"),
                            ("BYB", "Belarusian Ruble (1994–1999)"),
                            ("BYR", "Belarusian Ruble (2000–2016)"),
                            ("BEF", "Belgian Franc"),
                            ("BEC", "Belgian Franc (convertible)"),
                            ("BEL", "Belgian Franc (financial)"),
                            ("BZD", "Belize Dollar"),
                            ("BMD", "Bermudan Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BOL", "Bolivian Boliviano (1863–1963)"),
                            ("BOV", "Bolivian Mvdol"),
                            ("BOP", "Bolivian Peso"),
                            ("BAM", "Bosnia-Herzegovina Convertible Mark"),
                            ("BAD", "Bosnia-Herzegovina Dinar (1992–1994)"),
                            ("BAN", "Bosnia-Herzegovina New Dinar (1994–1997)"),
                            ("BWP", "Botswanan Pula"),
                            ("BRC", "Brazilian Cruzado (1986–1989)"),
                            ("BRZ", "Brazilian Cruzeiro (1942–1967)"),
                            ("BRE", "Brazilian Cruzeiro (1990–1993)"),
                            ("BRR", "Brazilian Cruzeiro (1993–1994)"),
                            ("BRN", "Brazilian New Cruzado (1989–1990)"),
                            ("BRB", "Brazilian New Cruzeiro (1967–1986)"),
                            ("BRL", "Brazilian Real"),
                            ("GBP", "British Pound"),
                            ("BND", "Brunei Dollar"),
                            ("BGL", "Bulgarian Hard Lev"),
                            ("BGN", "Bulgarian Lev"),
                            ("BGO", "Bulgarian Lev (1879–1952)"),
                            ("BGM", "Bulgarian Socialist Lev"),
                            ("BUK", "Burmese Kyat"),
                            ("BIF", "Burundian Franc"),
                            ("XPF", "CFP Franc"),
                            ("KHR", "Cambodian Riel"),
                            ("CAD", "Canadian Dollar"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("KYD", "Cayman Islands Dollar"),
                            ("XAF", "Central African CFA Franc"),
                            ("CLE", "Chilean Escudo"),
                            ("CLP", "Chilean Peso"),
                            ("CLF", "Chilean Unit of Account (UF)"),
                            ("CNX", "Chinese People’s Bank Dollar"),
                            ("CNY", "Chinese Yuan"),
                            ("CNH", "Chinese Yuan (offshore)"),
                            ("COP", "Colombian Peso"),
                            ("COU", "Colombian Real Value Unit"),
                            ("KMF", "Comorian Franc"),
                            ("CDF", "Congolese Franc"),
                            ("CRC", "Costa Rican Colón"),
                            ("HRD", "Croatian Dinar"),
                            ("HRK", "Croatian Kuna"),
                            ("CUC", "Cuban Convertible Peso"),
                            ("CUP", "Cuban Peso"),
                            ("CYP", "Cypriot Pound"),
                            ("CZK", "Czech Koruna"),
                            ("CSK", "Czechoslovak Hard Koruna"),
                            ("DKK", "Danish Krone"),
                            ("DJF", "Djiboutian Franc"),
                            ("DOP", "Dominican Peso"),
                            ("NLG", "Dutch Guilder"),
                            ("XCD", "East Caribbean Dollar"),
                            ("DDM", "East German Mark"),
                            ("ECS", "Ecuadorian Sucre"),
                            ("ECV", "Ecuadorian Unit of Constant Value"),
                            ("EGP", "Egyptian Pound"),
                            ("GQE", "Equatorial Guinean Ekwele"),
                            ("ERN", "Eritrean Nakfa"),
                            ("EEK", "Estonian Kroon"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("XBA", "European Composite Unit"),
                            ("XEU", "European Currency Unit"),
                            ("XBB", "European Monetary Unit"),
                            ("XBC", "European Unit of Account (XBC)"),
                            ("XBD", "European Unit of Account (XBD)"),
                            ("FKP", "Falkland Islands Pound"),
                            ("FJD", "Fijian Dollar"),
                            ("FIM", "Finnish Markka"),
                            ("FRF", "French Franc"),
                            ("XFO", "French Gold Franc"),
                            ("XFU", "French UIC-Franc"),
                            ("GMD", "Gambian Dalasi"),
                            ("GEK", "Georgian Kupon Larit"),
                            ("GEL", "Georgian Lari"),
                            ("DEM", "German Mark"),
                            ("GHS", "Ghanaian Cedi"),
                            ("GHC", "Ghanaian Cedi (1979–2007)"),
                            ("GIP", "Gibraltar Pound"),
                            ("XAU", "Gold"),
                            ("GRD", "Greek Drachma"),
                            ("GTQ", "Guatemalan Quetzal"),
                            ("GWP", "Guinea-Bissau Peso"),
                            ("GNF", "Guinean Franc"),
                            ("GNS", "Guinean Syli"),
                            ("GYD", "Guyanaese Dollar"),
                            ("HTG", "Haitian Gourde"),
                            ("HNL", "Honduran Lempira"),
                            ("HKD", "Hong Kong Dollar"),
                            ("HUF", "Hungarian Forint"),
                            ("IMP", "IMP"),
                            ("ISK", "Icelandic Króna"),
                            ("ISJ", "Icelandic Króna (1918–1981)"),
                            ("INR", "Indian Rupee"),
                            ("IDR", "Indonesian Rupiah"),
                            ("IRR", "Iranian Rial"),
                            ("IQD", "Iraqi Dinar"),
                            ("IEP", "Irish Pound"),
                            ("ILS", "Israeli New Shekel"),
                            ("ILP", "Israeli Pound"),
                            ("ILR", "Israeli Shekel (1980–1985)"),
                            ("ITL", "Italian Lira"),
                            ("JMD", "Jamaican Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("JOD", "Jordanian Dinar"),
                            ("KZT", "Kazakhstani Tenge"),
                            ("KES", "Kenyan Shilling"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("KGS", "Kyrgystani Som"),
                            ("LAK", "Laotian Kip"),
                            ("LVL", "Latvian Lats"),
                            ("LVR", "Latvian Ruble"),
                            ("LBP", "Lebanese Pound"),
                            ("LSL", "Lesotho Loti"),
                            ("LRD", "Liberian Dollar"),
                            ("LYD", "Libyan Dinar"),
                            ("LTL", "Lithuanian Litas"),
                            ("LTT", "Lithuanian Talonas"),
                            ("LUL", "Luxembourg Financial Franc"),
                            ("LUC", "Luxembourgian Convertible Franc"),
                            ("LUF", "Luxembourgian Franc"),
                            ("MOP", "Macanese Pataca"),
                            ("MKD", "Macedonian Denar"),
                            ("MKN", "Macedonian Denar (1992–1993)"),
                            ("MGA", "Malagasy Ariary"),
                            ("MGF", "Malagasy Franc"),
                            ("MWK", "Malawian Kwacha"),
                            ("MYR", "Malaysian Ringgit"),
                            ("MVR", "Maldivian Rufiyaa"),
                            ("MVP", "Maldivian Rupee (1947–1981)"),
                            ("MLF", "Malian Franc"),
                            ("MTL", "Maltese Lira"),
                            ("MTP", "Maltese Pound"),
                            ("MRU", "Mauritanian Ouguiya"),
                            ("MRO", "Mauritanian Ouguiya (1973–2017)"),
                            ("MUR", "Mauritian Rupee"),
                            ("MXV", "Mexican Investment Unit"),
                            ("MXN", "Mexican Peso"),
                            ("MXP", "Mexican Silver Peso (1861–1992)"),
                            ("MDC", "Moldovan Cupon"),
                            ("MDL", "Moldovan Leu"),
                            ("MCF", "Monegasque Franc"),
                            ("MNT", "Mongolian Tugrik"),
                            ("MAD", "Moroccan Dirham"),
                            ("MAF", "Moroccan Franc"),
                            ("MZE", "Mozambican Escudo"),
                            ("MZN", "Mozambican Metical"),
                            ("MZM", "Mozambican Metical (1980–2006)"),
                            ("MMK", "Myanmar Kyat"),
                            ("NAD", "Namibian Dollar"),
                            ("NPR", "Nepalese Rupee"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("TWD", "New Taiwan Dollar"),
                            ("NZD", "New Zealand Dollar"),
                            ("NIO", "Nicaraguan Córdoba"),
                            ("NIC", "Nicaraguan Córdoba (1988–1991)"),
                            ("NGN", "Nigerian Naira"),
                            ("KPW", "North Korean Won"),
                            ("NOK", "Norwegian Krone"),
                            ("OMR", "Omani Rial"),
                            ("PKR", "Pakistani Rupee"),
                            ("XPD", "Palladium"),
                            ("PAB", "Panamanian Balboa"),
                            ("PGK", "Papua New Guinean Kina"),
                            ("PYG", "Paraguayan Guarani"),
                            ("PEI", "Peruvian Inti"),
                            ("PEN", "Peruvian Sol"),
                            ("PES", "Peruvian Sol (1863–1965)"),
                            ("PHP", "Philippine Peso"),
                            ("XPT", "Platinum"),
                            ("PLN", "Polish Zloty"),
                            ("PLZ", "Polish Zloty (1950–1995)"),
                            ("PTE", "Portuguese Escudo"),
                            ("GWE", "Portuguese Guinea Escudo"),
                            ("QAR", "Qatari Rial"),
                            ("XRE", "RINET Funds"),
                            ("RHD", "Rhodesian Dollar"),
                            ("RON", "Romanian Leu"),
                            ("ROL", "Romanian Leu (1952–2006)"),
                            ("RUB", "Russian Ruble"),
                            ("RUR", "Russian Ruble (1991–1998)"),
                            ("RWF", "Rwandan Franc"),
                            ("SVC", "Salvadoran Colón"),
                            ("WST", "Samoan Tala"),
                            ("SAR", "Saudi Riyal"),
                            ("RSD", "Serbian Dinar"),
                            ("CSD", "Serbian Dinar (2002–2006)"),
                            ("SCR", "Seychellois Rupee"),
                            ("SLL", "Sierra Leonean Leone"),
                            ("XAG", "Silver"),
                            ("SGD", "Singapore Dollar"),
                            ("SKK", "Slovak Koruna"),
                            ("SIT", "Slovenian Tolar"),
                            ("SBD", "Solomon Islands Dollar"),
                            ("SOS", "Somali Shilling"),
                            ("ZAR", "South African Rand"),
                            ("ZAL", "South African Rand (financial)"),
                            ("KRH", "South Korean Hwan (1953–1962)"),
                            ("KRW", "South Korean Won"),
                            ("KRO", "South Korean Won (1945–1953)"),
                            ("SSP", "South Sudanese Pound"),
                            ("SUR", "Soviet Rouble"),
                            ("ESP", "Spanish Peseta"),
                            ("ESA", "Spanish Peseta (A account)"),
                            ("ESB", "Spanish Peseta (convertible account)"),
                            ("XDR", "Special Drawing Rights"),
                            ("LKR", "Sri Lankan Rupee"),
                            ("SHP", "St. Helena Pound"),
                            ("XSU", "Sucre"),
                            ("SDD", "Sudanese Dinar (1992–2007)"),
                            ("SDG", "Sudanese Pound"),
                            ("SDP", "Sudanese Pound (1957–1998)"),
                            ("SRD", "Surinamese Dollar"),
                            ("SRG", "Surinamese Guilder"),
                            ("SZL", "Swazi Lilangeni"),
                            ("SEK", "Swedish Krona"),
                            ("CHF", "Swiss Franc"),
                            ("SYP", "Syrian Pound"),
                            ("STN", "São Tomé & Príncipe Dobra"),
                            ("STD", "São Tomé & Príncipe Dobra (1977–2017)"),
                            ("TVD", "TVD"),
                            ("TJR", "Tajikistani Ruble"),
                            ("TJS", "Tajikistani Somoni"),
                            ("TZS", "Tanzanian Shilling"),
                            ("XTS", "Testing Currency Code"),
                            ("THB", "Thai Baht"),
                            (
                                "XXX",
                                "The codes assigned for transactions where no currency is involved",
                            ),
                            ("TPE", "Timorese Escudo"),
                            ("TOP", "Tongan Paʻanga"),
                            ("TTD", "Trinidad & Tobago Dollar"),
                            ("TND", "Tunisian Dinar"),
                            ("TRY", "Turkish Lira"),
                            ("TRL", "Turkish Lira (1922–2005)"),
                            ("TMT", "Turkmenistani Manat"),
                            ("TMM", "Turkmenistani Manat (1993–2009)"),
                            ("USD", "US Dollar"),
                            ("USN", "US Dollar (Next day)"),
                            ("USS", "US Dollar (Same day)"),
                            ("UGX", "Ugandan Shilling"),
                            ("UGS", "Ugandan Shilling (1966–1987)"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("UAK", "Ukrainian Karbovanets"),
                            ("AED", "United Arab Emirates Dirham"),
                            ("UYW", "Uruguayan Nominal Wage Index Unit"),
                            ("UYU", "Uruguayan Peso"),
                            ("UYP", "Uruguayan Peso (1975–1993)"),
                            ("UYI", "Uruguayan Peso (Indexed Units)"),
                            ("UZS", "Uzbekistani Som"),
                            ("VUV", "Vanuatu Vatu"),
                            ("VES", "Venezuelan Bolívar"),
                            ("VEB", "Venezuelan Bolívar (1871–2008)"),
                            ("VEF", "Venezuelan Bolívar (2008–2018)"),
                            ("VND", "Vietnamese Dong"),
                            ("VNN", "Vietnamese Dong (1978–1985)"),
                            ("CHE", "WIR Euro"),
                            ("CHW", "WIR Franc"),
                            ("XOF", "West African CFA Franc"),
                            ("YDD", "Yemeni Dinar"),
                            ("YER", "Yemeni Rial"),
                            ("YUN", "Yugoslavian Convertible Dinar (1990–1992)"),
                            ("YUD", "Yugoslavian Hard Dinar (1966–1990)"),
                            ("YUM", "Yugoslavian New Dinar (1994–2002)"),
                            ("YUR", "Yugoslavian Reformed Dinar (1992–1993)"),
                            ("ZWN", "ZWN"),
                            ("ZRN", "Zairean New Zaire (1993–1998)"),
                            ("ZRZ", "Zairean Zaire (1971–1993)"),
                            ("ZMW", "Zambian Kwacha"),
                            ("ZMK", "Zambian Kwacha (1968–2012)"),
                            ("ZWD", "Zimbabwean Dollar (1980–2008)"),
                            ("ZWR", "Zimbabwean Dollar (2008)"),
                            ("ZWL", "Zimbabwean Dollar (2009)"),
                        ],
                        default="GBP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="GBP",
                        max_digits=14,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("year", "Year"),
                            ("month", "Month"),
                            ("week", "Week"),
                            ("day", "Day"),
                        ],
                        default="month",
                        max_length=10,
                    ),
                ),
                ("interval_count", models.IntegerField(blank=True, default=1)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="app.membershipplanpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
