# Generated by Django 4.0.4 on 2022-04-27 14:33

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import app.models.wagtail


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_homepage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "membership_options",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        default="Choose your plan",
                                        form_classname="full title",
                                        null=True,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        blank=True,
                                        default="<p>Your subscription will begin with the most recently published book in your chosen collection.</p>",
                                        null=True,
                                    ),
                                ),
                                (
                                    "plans",
                                    wagtail.blocks.ListBlock(
                                        app.models.blocks.PlanBlock
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
