# Generated by Django 4.0.4 on 2022-04-28 07:31

import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_rename_page_membershipplanprice_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplanpage",
            name="pick_product_title",
            field=models.CharField(
                blank=True,
                default="Choose a book series",
                help_text="Displayed if there are multiple products to pick from",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membershipplanpage",
            name="pick_product_text",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="Displayed if there are multiple products to pick from",
                null=True,
            ),
        ),
    ]
