# Generated by Django 4.0.4 on 2022-04-28 14:31

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_membershipplanprice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplanprice",
            name="free_shipping_zones",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="Waive shipping fees for customers in these shipping zones.",
                related_name="excluded_prices",
                to="app.shippingzone",
            ),
        ),
    ]
