# Generated by Django 4.0.4 on 2022-04-28 15:38

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_membershipplanprice_free_shipping_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplanprice",
            name="free_shipping_zones",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Waive shipping fees for customers in these shipping zones.",
                related_name="excluded_prices",
                to="app.shippingzone",
            ),
        ),
    ]
