# Generated by Django 4.0.4 on 2022-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_homepage_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address1",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address2",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="old_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tel",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
