# Generated by Django 4.0.4 on 2022-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_user_address1_user_address2_user_birthday_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="old_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
