# Generated by Django 4.0.4 on 2022-04-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0001_initial"),
        ("app", "0029_alter_user_old_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyGifts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_id", models.CharField(max_length=500, unique=True)),
                ("gift_code", models.CharField(blank=True, max_length=500)),
                ("giving_user_email", models.CharField(blank=True, max_length=500)),
                (
                    "initial_recipient_email",
                    models.CharField(blank=True, max_length=500),
                ),
                ("migrated", models.BooleanField(default=False)),
                (
                    "giving_sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="legacy_gift_record",
                        to="djstripe.subscription",
                        to_field="id",
                    ),
                ),
                (
                    "giving_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="legacy_gifts_given",
                        to=settings.AUTH_USER_MODEL,
                        to_field="old_id",
                    ),
                ),
                (
                    "recipient_user_matching_gift_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="legacy_gifts_received",
                        to=settings.AUTH_USER_MODEL,
                        to_field="old_id",
                    ),
                ),
            ],
        ),
    ]
