# Generated by Django 4.0.4 on 2022-04-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from app.utils.django import migrate_streamfield_name


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010_alter_customer_balance"),
        ("app", "0029_alter_user_old_id"),
    ]

    operations = [
        migrate_streamfield_name(
            lambda apps: apps.get_model("app.HomePage"),
            "layout",
            "text",
            "one_column_heading_and_text",
        ),
        migrate_streamfield_name(
            lambda apps: apps.get_model("app.HomePage"),
            "layout",
            "list",
            "list_of_heading_image_text",
        ),
    ]
