# Generated by Django 4.0.4 on 2022-05-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_remove_informationpage_body_informationpage_layout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informationpage",
            name="cover_image",
        ),
    ]
