# Generated by Django 4.0.4 on 2022-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_legacygifts_giving_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legacygifts",
            name="giving_sub",
        ),
        migrations.AlterField(
            model_name="legacygifts",
            name="giving_user",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="legacygifts",
            name="recipient_user_matching_gift_email",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
