# Generated by Django 4.0.4 on 2022-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_remove_legacygifts_giving_sub_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacygifts",
            name="giving_sub",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
