# Generated by Django 4.0.4 on 2022-05-03 21:07

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_legacygifts_giving_sub"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipplanpage",
            name="products",
        ),
        migrations.AddField(
            model_name="membershipplanprice",
            name="products",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="app.lbcproduct"
            ),
        ),
    ]
