# Generated by Django 4.0.4 on 2022-05-04 09:55

import django.contrib.postgres.fields
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_remove_membershipplanpage_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookpage",
            name="authors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=300),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="description",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="forward_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=300),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="isbn",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="original_publisher",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
