# Generated by Django 4.0.4 on 2022-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_alter_bookindexpage_layout_alter_homepage_layout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shopify_customer_id",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
