# Generated by Django 4.0.4 on 2022-05-07 23:54

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations

import app.models.wagtail


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_membershipplanpage_layout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplanpage",
            name="layout",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "membership_options",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        blank=True,
                                        default="Choose your plan",
                                        form_classname="full title",
                                        null=True,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.RichTextBlock(
                                        blank=True,
                                        default="<p>Your subscription will begin with the most recently published book in your chosen collection.</p>",
                                        null=True,
                                    ),
                                ),
                                (
                                    "plans",
                                    wagtail.core.blocks.ListBlock(
                                        app.models.wagtail.PlanBlock
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "featured_book",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "book",
                                    wagtail.core.blocks.PageChooserBlock(
                                        can_choose_root=False,
                                        page_type=["app.BookPage"],
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-black text-white", "black"),
                                            ("bg-white", "white"),
                                            ("tw-bg-yellow", "yellow"),
                                            ("tw-bg-teal", "teal"),
                                            ("tw-bg-darkgreen", "darkgreen"),
                                            ("tw-bg-lilacgrey", "lilacgrey"),
                                            ("tw-bg-coral", "coral"),
                                            ("tw-bg-purple", "purple"),
                                            ("tw-bg-magenta", "magenta"),
                                            ("tw-bg-pink", "pink"),
                                            ("tw-bg-lightgreen", "lightgreen"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "promotion_label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Label that highlights this product",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.RichTextBlock(
                                        help_text="This will replace the book's default description. You can use this to provide a more contextualised description of the book",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "book_selection",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "column_width",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "small"),
                                            ("medium", "medium"),
                                            ("large", "large"),
                                        ]
                                    ),
                                ),
                                (
                                    "books",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.PageChooserBlock(
                                            can_choose_root=False,
                                            page_type=["app.BookPage"],
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "recently_published_books",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "column_width",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "small"),
                                            ("medium", "medium"),
                                            ("large", "large"),
                                        ]
                                    ),
                                ),
                                (
                                    "max_books",
                                    wagtail.core.blocks.IntegerBlock(
                                        default=4,
                                        help_text="How many books should show up?",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "hero_text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        form_classname="full title", max_length=250
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-black text-white", "black"),
                                            ("bg-white", "white"),
                                            ("tw-bg-yellow", "yellow"),
                                            ("tw-bg-teal", "teal"),
                                            ("tw-bg-darkgreen", "darkgreen"),
                                            ("tw-bg-lilacgrey", "lilacgrey"),
                                            ("tw-bg-coral", "coral"),
                                            ("tw-bg-purple", "purple"),
                                            ("tw-bg-magenta", "magenta"),
                                            ("tw-bg-pink", "pink"),
                                            ("tw-bg-lightgreen", "lightgreen"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    max_length=100, required=False
                                                ),
                                            ),
                                            (
                                                "page",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text="Pick a page or specify a URL",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "href",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text="Pick a page or specify a URL",
                                                    label="URL",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("sm", "small"),
                                                        ("md", "medium"),
                                                        ("lg", "large"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        (
                                                            "btn-outline-dark",
                                                            "outlined",
                                                        ),
                                                        (
                                                            "btn-dark text-yellow",
                                                            "filled",
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    (
                        "richtext",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "h1",
                                            "h2",
                                            "h3",
                                            "h4",
                                            "h5",
                                            "bold",
                                            "italic",
                                            "link",
                                            "ol",
                                            "ul",
                                            "hr",
                                            "link",
                                            "document-link",
                                            "image",
                                            "embed",
                                            "blockquote",
                                        ],
                                        form_classname="full",
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "left"),
                                            ("center", "center"),
                                            ("right", "right"),
                                        ],
                                        help_text="Doesn't apply when used inside a column.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "list_of_heading_image_text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "column_width",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "small"),
                                            ("medium", "medium"),
                                            ("large", "large"),
                                        ]
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.core.blocks.ListBlock(
                                        app.models.wagtail.ListItemBlock
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "single_column",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-black text-white", "black"),
                                            ("bg-white", "white"),
                                            ("tw-bg-yellow", "yellow"),
                                            ("tw-bg-teal", "teal"),
                                            ("tw-bg-darkgreen", "darkgreen"),
                                            ("tw-bg-lilacgrey", "lilacgrey"),
                                            ("tw-bg-coral", "coral"),
                                            ("tw-bg-purple", "purple"),
                                            ("tw-bg-magenta", "magenta"),
                                            ("tw-bg-pink", "pink"),
                                            ("tw-bg-lightgreen", "lightgreen"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "hero_text",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.core.blocks.CharBlock(
                                                                form_classname="full title",
                                                                max_length=250,
                                                            ),
                                                        ),
                                                        (
                                                            "background_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "bg-black text-white",
                                                                        "black",
                                                                    ),
                                                                    (
                                                                        "bg-white",
                                                                        "white",
                                                                    ),
                                                                    (
                                                                        "tw-bg-yellow",
                                                                        "yellow",
                                                                    ),
                                                                    (
                                                                        "tw-bg-teal",
                                                                        "teal",
                                                                    ),
                                                                    (
                                                                        "tw-bg-darkgreen",
                                                                        "darkgreen",
                                                                    ),
                                                                    (
                                                                        "tw-bg-lilacgrey",
                                                                        "lilacgrey",
                                                                    ),
                                                                    (
                                                                        "tw-bg-coral",
                                                                        "coral",
                                                                    ),
                                                                    (
                                                                        "tw-bg-purple",
                                                                        "purple",
                                                                    ),
                                                                    (
                                                                        "tw-bg-magenta",
                                                                        "magenta",
                                                                    ),
                                                                    (
                                                                        "tw-bg-pink",
                                                                        "pink",
                                                                    ),
                                                                    (
                                                                        "tw-bg-lightgreen",
                                                                        "lightgreen",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "button",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "text",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            max_length=100,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            help_text="Pick a page or specify a URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "href",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            help_text="Pick a page or specify a URL",
                                                                            label="URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "size",
                                                                        wagtail.core.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "sm",
                                                                                    "small",
                                                                                ),
                                                                                (
                                                                                    "md",
                                                                                    "medium",
                                                                                ),
                                                                                (
                                                                                    "lg",
                                                                                    "large",
                                                                                ),
                                                                            ],
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "style",
                                                                        wagtail.core.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "btn-outline-dark",
                                                                                    "outlined",
                                                                                ),
                                                                                (
                                                                                    "btn-dark text-yellow",
                                                                                    "filled",
                                                                                ),
                                                                            ],
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "title_image_caption",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.core.blocks.CharBlock(
                                                                form_classname="full title",
                                                                max_length=250,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "image_css",
                                                            wagtail.core.blocks.CharBlock(
                                                                max_length=500,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.RichTextBlock(
                                                                max_length=500
                                                            ),
                                                        ),
                                                        (
                                                            "background_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "bg-black text-white",
                                                                        "black",
                                                                    ),
                                                                    (
                                                                        "bg-white",
                                                                        "white",
                                                                    ),
                                                                    (
                                                                        "tw-bg-yellow",
                                                                        "yellow",
                                                                    ),
                                                                    (
                                                                        "tw-bg-teal",
                                                                        "teal",
                                                                    ),
                                                                    (
                                                                        "tw-bg-darkgreen",
                                                                        "darkgreen",
                                                                    ),
                                                                    (
                                                                        "tw-bg-lilacgrey",
                                                                        "lilacgrey",
                                                                    ),
                                                                    (
                                                                        "tw-bg-coral",
                                                                        "coral",
                                                                    ),
                                                                    (
                                                                        "tw-bg-purple",
                                                                        "purple",
                                                                    ),
                                                                    (
                                                                        "tw-bg-magenta",
                                                                        "magenta",
                                                                    ),
                                                                    (
                                                                        "tw-bg-pink",
                                                                        "pink",
                                                                    ),
                                                                    (
                                                                        "tw-bg-lightgreen",
                                                                        "lightgreen",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "button",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "text",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            max_length=100,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            help_text="Pick a page or specify a URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "href",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            help_text="Pick a page or specify a URL",
                                                                            label="URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "size",
                                                                        wagtail.core.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "sm",
                                                                                    "small",
                                                                                ),
                                                                                (
                                                                                    "md",
                                                                                    "medium",
                                                                                ),
                                                                                (
                                                                                    "lg",
                                                                                    "large",
                                                                                ),
                                                                            ],
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "style",
                                                                        wagtail.core.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "btn-outline-dark",
                                                                                    "outlined",
                                                                                ),
                                                                                (
                                                                                    "btn-dark text-yellow",
                                                                                    "filled",
                                                                                ),
                                                                            ],
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "single_book",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "book",
                                                            wagtail.core.blocks.PageChooserBlock(
                                                                can_choose_root=False,
                                                                page_type=[
                                                                    "app.BookPage"
                                                                ],
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "membership_plan",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "plan",
                                                            wagtail.core.blocks.PageChooserBlock(
                                                                can_choose_root=False,
                                                                page_type=[
                                                                    "app.MembershipPlanPage"
                                                                ],
                                                            ),
                                                        ),
                                                        (
                                                            "background_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "bg-black text-white",
                                                                        "black",
                                                                    ),
                                                                    (
                                                                        "bg-white",
                                                                        "white",
                                                                    ),
                                                                    (
                                                                        "tw-bg-yellow",
                                                                        "yellow",
                                                                    ),
                                                                    (
                                                                        "tw-bg-teal",
                                                                        "teal",
                                                                    ),
                                                                    (
                                                                        "tw-bg-darkgreen",
                                                                        "darkgreen",
                                                                    ),
                                                                    (
                                                                        "tw-bg-lilacgrey",
                                                                        "lilacgrey",
                                                                    ),
                                                                    (
                                                                        "tw-bg-coral",
                                                                        "coral",
                                                                    ),
                                                                    (
                                                                        "tw-bg-purple",
                                                                        "purple",
                                                                    ),
                                                                    (
                                                                        "tw-bg-magenta",
                                                                        "magenta",
                                                                    ),
                                                                    (
                                                                        "tw-bg-pink",
                                                                        "pink",
                                                                    ),
                                                                    (
                                                                        "tw-bg-lightgreen",
                                                                        "lightgreen",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "promotion_label",
                                                            wagtail.core.blocks.CharBlock(
                                                                help_text="Label that highlights this product",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "richtext",
                                                wagtail.core.blocks.RichTextBlock(
                                                    features=[
                                                        "h1",
                                                        "h2",
                                                        "h3",
                                                        "h4",
                                                        "h5",
                                                        "bold",
                                                        "italic",
                                                        "link",
                                                        "ol",
                                                        "ul",
                                                        "hr",
                                                        "link",
                                                        "document-link",
                                                        "image",
                                                        "embed",
                                                        "blockquote",
                                                    ]
                                                ),
                                            ),
                                            (
                                                "button",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "text",
                                                            wagtail.core.blocks.CharBlock(
                                                                max_length=100,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.core.blocks.PageChooserBlock(
                                                                help_text="Pick a page or specify a URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "href",
                                                            wagtail.core.blocks.URLBlock(
                                                                help_text="Pick a page or specify a URL",
                                                                label="URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "size",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("sm", "small"),
                                                                    ("md", "medium"),
                                                                    ("lg", "large"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "style",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-outline-dark",
                                                                        "outlined",
                                                                    ),
                                                                    (
                                                                        "btn-dark text-yellow",
                                                                        "filled",
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "column_width",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "small"),
                                            ("medium", "medium"),
                                            ("large", "large"),
                                        ]
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "left"),
                                            ("center", "center"),
                                            ("right", "right"),
                                        ],
                                        help_text="Doesn't apply when used inside a column.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "columns",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-black text-white", "black"),
                                            ("bg-white", "white"),
                                            ("tw-bg-yellow", "yellow"),
                                            ("tw-bg-teal", "teal"),
                                            ("tw-bg-darkgreen", "darkgreen"),
                                            ("tw-bg-lilacgrey", "lilacgrey"),
                                            ("tw-bg-coral", "coral"),
                                            ("tw-bg-purple", "purple"),
                                            ("tw-bg-magenta", "magenta"),
                                            ("tw-bg-pink", "pink"),
                                            ("tw-bg-lightgreen", "lightgreen"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "columns",
                                    wagtail.core.blocks.ListBlock(
                                        app.models.wagtail.ColumnBlock,
                                        max_num=5,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("newsletter_signup", wagtail.core.blocks.StructBlock([])),
                    ("plan_title", app.models.wagtail.PlanTitleBlock()),
                    ("plan_pricing", app.models.wagtail.PlanPricingBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
