# Generated by Django 4.0.4 on 2022-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_alter_blogpage_body_alter_bookindexpage_layout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookpage",
            name="type",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
