# Generated by Django 4.0.7 on 2022-08-29 09:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_mappage_alter_blogindexpage_struct_org_actions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
