# Generated by Django 4.0.7 on 2022-09-23 17:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_circleevent_body_html_circleevent_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchandisepage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
