# Generated by Django 4.0.7 on 2022-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_merchandisepage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchandisepage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
