# Generated by Django 4.0.8 on 2022-12-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_bookpage_cached_price_merchandisepage_cached_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplanprice",
            name="should_advertise_postage_price",
            field=models.BooleanField(
                default=True,
                help_text="Whether to advertise that the price is + p&p, before the shipping zone is known.",
            ),
        ),
    ]
