# Generated by Django 4.0.8 on 2022-12-19 18:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_membershipplanprice_should_advertise_postage_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplanprice",
            name="products",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="The stripe product that the user will be subscribed to. If multiple products are set here, then the user will be asked to pick which one they want, e.g. Classic or Contemporary books.",
                to="app.lbcproduct",
            ),
        ),
        migrations.CreateModel(
            name="Upsell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("description", models.CharField(max_length=150)),
                (
                    "from_stripe_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsells",
                        to="app.lbcproduct",
                    ),
                ),
                (
                    "plan",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsells",
                        to="app.membershipplanpage",
                        verbose_name="membership plan",
                    ),
                ),
                (
                    "to_stripe_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="app.lbcproduct",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("plan", "from_stripe_product", "to_stripe_product")
                },
            },
        ),
    ]
