# Generated by Django 4.0.8 on 2023-02-07 16:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_alter_bookindexpage_layout_alter_bookpage_layout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upsellplansettings",
            name="donation_text",
            field=wagtail.fields.RichTextField(
                default="\n    <p>If you have remained on a legacy or a standard price, please consider adding a monthly donation to your membership fee. Any amount, however small, will make a huge difference. Thank you!</p>\n    "
            ),
        ),
        migrations.AddField(
            model_name="upsellplansettings",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                default="\n    <h1>Review your fee</h1><p>\n    <p>Since you signed up, our operating costs have increased dramatically due to the economic times we’re all living through.</p>\n    <p>We’ve increased the price of new memberships and protected your fee, but we are beginning to struggle. Can you afford to increase your membership fee?</p>\n    "
            ),
        ),
        migrations.AlterField(
            model_name="circleevent",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
