# Generated by Django 4.0.8 on 2023-07-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_alter_upsellplansettings_upgrade_membership_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookpage",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="bookpage",
            name="forward_by",
        ),
        migrations.RemoveField(
            model_name="bookpage",
            name="image_urls",
        ),
        migrations.RemoveField(
            model_name="merchandisepage",
            name="image_urls",
        ),
    ]
