# Generated by Django 4.0.8 on 2023-11-22 15:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_membershipplanpage_benefits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplanpage",
            name="benefits",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="List of pithy beneficial features of this plan",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membershipplanprice",
            name="benefits",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="List of pithy beneficial features of this plan",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syllabuspage",
            name="book_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classic", "classic"),
                    ("contemporary", "contemporary"),
                    ("all-books", "all-books"),
                ],
                default="all-books",
                help_text="Used to display relevant books",
                max_length=100,
            ),
        ),
    ]
