# Generated by Django 4.2 on 2024-01-15 16:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_alter_customimage_file_alter_imagerendition_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Bullet points will appear as ticks.",
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("year", "Year"),
                            ("month", "Month"),
                            ("week", "Week"),
                            ("day", "Day"),
                        ],
                        default="month",
                        max_length=10,
                    ),
                ),
                ("interval_count", models.IntegerField(blank=True, default=1)),
                (
                    "banner_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.customimage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="membershipplanpage",
            name="syllabi",
        ),
        migrations.DeleteModel(
            name="SyllabusPage",
        ),
        migrations.AddField(
            model_name="readingoption",
            name="plans",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="The plans available under this option",
                related_name="plans",
                to="app.membershipplanpage",
            ),
        ),
    ]
