# Generated by Django 4.2 on 2024-01-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_readingoption_remove_membershipplanpage_syllabi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplanpage",
            name="book_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classic", "classic"),
                    ("contemporary", "contemporary"),
                    ("all-books", "all-books"),
                ],
                help_text="Which types of books are included in this plan? Used for displaying things.",
                max_length=150,
                null=True,
            ),
        ),
    ]
