# Generated by Django 4.2 on 2024-01-16 13:02

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_membershipplanpage_book_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplanprice",
            name="products",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="The stripe product that the user will be subscribed to.",
                to="app.lbcproduct",
                verbose_name="Stripe product",
            ),
        ),
        migrations.AlterField(
            model_name="readingoption",
            name="title",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
