# Generated by Django 4.2 on 2024-01-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_remove_membershipplanpage_benefits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplanpage",
            name="product_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.customimage",
            ),
        ),
    ]
