# Generated by Django 4.2 on 2024-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_membershipplanpage_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplanprice",
            name="skip_donation_ask",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
