# Generated by Django 4.2 on 2024-01-16 19:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("app", "0080_membershipplanprice_default_donation_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2SignupFlow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "continue_button_label",
                    models.CharField(
                        default="Continue",
                        help_text="Label for the continue button",
                        max_length=255,
                    ),
                ),
                (
                    "select_deliveries_title",
                    models.CharField(
                        default="How often do you want a new book?",
                        help_text="Title for the deliveries step",
                        max_length=255,
                    ),
                ),
                (
                    "select_syllabus_title",
                    models.CharField(
                        default="What kind of books do you want?",
                        help_text="Title for the syllabus step",
                        max_length=255,
                    ),
                ),
                (
                    "select_syllabus_intro",
                    wagtail.fields.RichTextField(
                        default="\n        <p>Each syllabus has a new book published for it regularly.</p>\n        "
                    ),
                ),
                (
                    "select_shipping_title",
                    models.CharField(
                        default="Where should we send your books?",
                        help_text="Title for the shipping step",
                        max_length=255,
                    ),
                ),
                (
                    "select_billing_title",
                    models.CharField(
                        default="How much do you want to pay?",
                        help_text="Title for the billing step",
                        max_length=255,
                    ),
                ),
                (
                    "select_donation_intro",
                    wagtail.fields.RichTextField(
                        default="\n          <p>Our membership fees are based on solidarity. If you can afford to pay more, you'll help us to keep our fees low for everyone.</p>\n          <p>To learn more about our not-for-profit political education project, <a href='/about' target='_blank' rel='noopener noreferrer'>click here</a>.\n        "
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
