# Generated by Django 4.2 on 2025-04-08 14:37

import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0082_alter_membershipplanprice_default_donation_amount_currency_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("start_date", models.DateTimeField()),
                ("location_type", models.CharField(max_length=300)),
                (
                    "in_person_location",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("virtual_location_url", models.URLField(max_length=1024)),
                (
                    "as_geojson_feature",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "frequency_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                        ],
                        help_text="Select the frequency for recurring events",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
