# Generated by Django 4.2 on 2025-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="url",
            new_name="online_url",
        ),
        migrations.RemoveField(
            model_name="event",
            name="as_geojson_feature",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location_type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="virtual_location_url",
        ),
        migrations.AddField(
            model_name="event",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="postcode",
            field=models.CharField(
                blank=True,
                help_text="Enter a UK postcode to auto-calculate coordinates",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="in_person_location",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
