# Generated by Django 4.2 on 2025-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0084_rename_url_event_online_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="coordinates",
        ),
    ]
