# Generated by Django 4.2 on 2025-04-08 15:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0085_remove_event_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
