# Generated by Django 4.2 on 2025-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0086_event_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="online_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
