# Generated by Django 4.2 on 2025-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0087_alter_event_online_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
