# Generated by Django 4.2 on 2025-04-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_eventsubmissionpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrencePattern",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("day_of_week", models.CharField(blank=True, max_length=2, null=True)),
                ("week_of_month", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="frequency_interval",
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.recurrencepattern",
            ),
        ),
    ]
