# Generated by Django 4.2 on 2025-04-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0090_recurrencepattern_remove_event_frequency_interval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventIntervals",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        help_text="How often the event repeats: daily, weekly, or monthly.",
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Repeats every X units of the selected frequency. For example, every 2 weeks.",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MO", "Monday"),
                            ("TU", "Tuesday"),
                            ("WE", "Wednesday"),
                            ("TH", "Thursday"),
                            ("FR", "Friday"),
                            ("SA", "Saturday"),
                            ("SU", "Sunday"),
                        ],
                        help_text="Used for weekly or monthly patterns. Select the day of the week on which the event should occur, e.g., Thursday.",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "week_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Used for monthly patterns. Enter 1 for the first week, 2 for the second, up to 4. Use -1 for the last week of the month. For example, '3' and 'Thursday' = third Thursday of the month.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.eventintervals",
            ),
        ),
        migrations.DeleteModel(
            name="RecurrencePattern",
        ),
    ]
