# Generated by Django 4.2 on 2025-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_eventintervals_alter_event_recurrence_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventIntervals",
            new_name="EventInterval",
        ),
    ]
