# Generated by Django 4.2 on 2025-04-10 13:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0092_rename_eventintervals_eventinterval"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="recurrence",
        ),
        migrations.DeleteModel(
            name="EventInterval",
        ),
        migrations.AddField(
            model_name="eventdate",
            name="event",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_dates",
                to="app.event",
            ),
        ),
    ]
