# Generated by Django 4.2 on 2025-04-10 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_eventdate_remove_event_recurrence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=500)),
                ("next_event", models.DateTimeField()),
                ("is_online", models.BooleanField(default=False)),
                ("in_person_location", models.CharField(max_length=500)),
                (
                    "in_person_postcode",
                    models.CharField(
                        blank=True,
                        help_text="Enter a UK postcode to show your event on our map.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("online_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("description", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["next_event"],
            },
        ),
        migrations.AlterField(
            model_name="eventdate",
            name="event",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_dates",
                to="app.readinggroup",
            ),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
