# Generated by Django 4.2 on 2025-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_readinggroup_alter_eventdate_event_delete_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinggroup",
            name="in_person_location",
            field=models.CharField(
                blank=True,
                help_text="Enter a location if your event is in person.",
                max_length=500,
                null=True,
            ),
        ),
    ]
