# Generated by Django 4.2 on 2025-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_remove_readinggroup_online_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readinggroup",
            name="description",
        ),
        migrations.AddField(
            model_name="readinggroup",
            name="recurring_pattern",
            field=models.CharField(
                blank=True,
                help_text="Enter a description of the recurring pattern, e.g. 'Every first Monday of the month'.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="readinggroup",
            name="in_person_location",
            field=models.CharField(
                blank=True,
                help_text="Enter an address if your event is in person.",
                max_length=500,
                null=True,
            ),
        ),
    ]
