# Generated by Django 4.2 on 2025-04-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("app", "0097_remove_readinggroup_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventSubmissionPage",
            new_name="ReadingGroupSubmission",
        ),
    ]
