# Generated by Django 4.2 on 2025-04-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_readinggroup_join_email_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readinggroup",
            old_name="join_email_address",
            new_name="contact_email_address",
        ),
    ]
