# Generated by Django 4.2 on 2025-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0101_rename_join_email_address_readinggroup_contact_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinggroup",
            name="next_event",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
