# Generated by Django 4.2 on 2025-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0102_alter_readinggroup_next_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readinggroup",
            old_name="join_contact_link",
            new_name="join_link_or_email",
        ),
        migrations.AlterField(
            model_name="readinggroup",
            name="join_link_or_email",
            field=models.CharField(
                blank=True,
                help_text="(Optional) A link or email address to join the group.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="readinggroup",
            name="contact_email_address",
            field=models.EmailField(
                help_text="(Private) We will use this to contact you.", max_length=1024
            ),
        ),
    ]
