# Generated by Django 4.2 on 2025-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0105_readinggroup_timezone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readinggroup",
            old_name="join_link_or_email",
            new_name="contact_link_or_email",
        ),
    ]
