# Generated by Django 4.2 on 2026-01-21 12:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0106_remove_readinggroup_join_link_or_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinggroup",
            name="country",
            field=django_countries.fields.CountryField(default="GB", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="readinggroup",
            name="contact_link_or_email",
            field=models.CharField(
                blank=True,
                help_text="(Optional) A link or email address to contact the group.",
                max_length=128,
                null=True,
            ),
        ),
    ]
