# Generated by Django 4.2 on 2026-01-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0107_readinggroup_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readinggroup",
            old_name="country",
            new_name="in_person_country",
        ),
    ]
