name: Regular Server Restart
on:
  schedule:
    - cron: "0 */12 * * *"
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    environment:
      name: production
      url: https://leftbookclub.com
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps restart lbc-production
      - run: flyctl apps restart lbc-worker-production
      - run: flyctl pg restart lbc-pg-production
